# Generated by Django 3.0.5 on 2020-04-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime']},
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
